### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Glavic** [kirves/go-form-it#6]
Hi,
do you have any plan of implementing validation? 
How do you currently solve validation and show errors to user?
BR

**Comment by kirves** [comment]
Hi,
I have no plan of implementing validation since I have no time to get back to this project.
Anyway, if you perform server-side validation (which you should) you can add error messages to single fields and they will be correctly rendered with the form.

**Comment by Glavic** [comment]
I did mean server-side validations. Sad to hear that you don't have time for this great project :(
Tnx
